### ISSUE TITLE
Configuration validation

### ISSUE THREAD

**Issue by ghost** [Sxtanna/KDatabases#1]
Make sure you validate the configurations:

[Fixed the goddamn link because you told me to](https://github.com/Sxtanna/KDatabases/blob/master/Kuery/src/main/kotlin/com/sxtanna/db/config/KueryConfig.kt)

**Comment by Sxtanna** [comment]
LOL

**Comment by Sxtanna** [comment]
Thkx though bb, I'll do it

**Comment by Sxtanna** [comment]
addressed in 713f4e7
